- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    aws_access_key: ...
    aws_secret_key: ...
  tasks:
    - name: deploy service
      ecs_service:
        region: "us-east-1"
        name: first-run-test
        launch_type: "FARGATE"
        network_configuration:
          awsvpc_configuration:
            subnets:
              - subnet-ed97c7d2
            security_groups: []
            assign_public_ip: DISABLED
        state: present
        cluster: test-fargate
        task_definition: 'first-run-task-definition'
        desired_count: 1
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
